# Generated by Django 6.0.5 on 2026-05-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('years_of_experience', models.IntegerField()),
                ('base_salary', models.IntegerField()),
                ('bonus', models.IntegerField(default=0)),
                ('stock_rsu', models.IntegerField(default=0)),
                ('total_compensation', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField()),
                ('overall_score', models.IntegerField(blank=True, null=True)),
                ('rule_score', models.IntegerField(blank=True, null=True)),
                ('ai_score', models.IntegerField(blank=True, null=True)),
                ('confidence_level', models.CharField(blank=True, max_length=20, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('flags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
